const SUBSCRIPTION_PENDING_STATUS = 0;
const SUBSCRIPTION_ACCEPTED_STATUS = 1;
const SUBSCRIPTION_DECLINED_STATUS = 2;

const SUBSCRIPTION_STATUSES = [
    SUBSCRIPTION_PENDING_STATUS,
    SUBSCRIPTION_ACCEPTED_STATUS,
    SUBSCRIPTION_DECLINED_STATUS
];